alter table CETRD_CUSTOMER add constraint FK_CETRD_CUSTOMER_CUSTOMER_TYPE foreign key (CUSTOMER_TYPE_ID) references CETRD_CUSTOMER_TYPE(ID);
create index IDX_CETRD_CUSTOMER_CUSTOMER_TYPE on CETRD_CUSTOMER (CUSTOMER_TYPE_ID);
