-- begin CETRD_ORDER
alter table CETRD_ORDER add constraint FK_CETRD_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references CETRD_CUSTOMER(ID)^
alter table CETRD_ORDER add constraint FK_CETRD_ORDER_PAYMENT_METHOD foreign key (PAYMENT_METHOD_ID) references CETRD_PAYMENT_METHOD(ID)^
alter table CETRD_ORDER add constraint FK_CETRD_ORDER_TAX_RATE foreign key (TAX_RATE_ID) references CETRD_TAX_RATE(ID)^
create index IDX_CETRD_ORDER_PAYMENT_METHOD on CETRD_ORDER (PAYMENT_METHOD_ID)^
create index IDX_CETRD_ORDER_TAX_RATE on CETRD_ORDER (TAX_RATE_ID)^
create index IDX_CETRD_ORDER_CUSTOMER on CETRD_ORDER (CUSTOMER_ID)^
-- end CETRD_ORDER
-- begin CETRD_CUSTOMER
alter table CETRD_CUSTOMER add constraint FK_CETRD_CUSTOMER_CUSTOMER_TYPE_ID foreign key (CUSTOMER_TYPE_ID) references CETRD_CUSTOMER_TYPE(ID)^
alter table CETRD_CUSTOMER add constraint FK_CETRD_CUSTOMER_PREFERRED_PAYMENT_METHOD_ID foreign key (PREFERRED_PAYMENT_METHOD_ID) references CETRD_PAYMENT_METHOD(ID)^
create index IDX_CETRD_CUSTOMER_PREFERRED_PAYMENT_METHOD on CETRD_CUSTOMER (PREFERRED_PAYMENT_METHOD_ID)^
create index IDX_CETRD_CUSTOMER_CUSTOMER_TYPE on CETRD_CUSTOMER (CUSTOMER_TYPE_ID)^
-- end CETRD_CUSTOMER
-- begin CETRD_TENANT_CUSTOMER_TYPE
alter table CETRD_TENANT_CUSTOMER_TYPE add constraint FK_CETRD_TENANT_CUSTOMER_TYPE_CUSTOMER_TYPE foreign key (CUSTOMER_TYPE_ID) references CETRD_CUSTOMER_TYPE(ID)^
alter table CETRD_TENANT_CUSTOMER_TYPE add constraint FK_CETRD_TENANT_CUSTOMER_TYPE_TENANT foreign key (TENANT_ID) references CETRD_TENANT(ID)^
create unique index IDX_CETRD_TENANT_CUSTOMER_TYPE_UNQ on CETRD_TENANT_CUSTOMER_TYPE (CUSTOMER_TYPE_ID, TENANT_ID, DELETE_TS) ^
create index IDX_CETRD_TENANT_CUSTOMER_TYPE_TENANT on CETRD_TENANT_CUSTOMER_TYPE (TENANT_ID)^
create index IDX_CETRD_TENANT_CUSTOMER_TYPE_CUSTOMER_TYPE on CETRD_TENANT_CUSTOMER_TYPE (CUSTOMER_TYPE_ID)^
-- end CETRD_TENANT_CUSTOMER_TYPE
